### 회원가입
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "asdf",
  "email": "asdf@example.com",
  "password": "123"
}

### 유저 조회
GET http://localhost:8081/users/asdf

### 로그인 - 확인차
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "user_id": "asdf",
  "password": "123"
}

### 상태
PUT http://localhost:8080/accountapi/users/asdf/status
Content-Type: application/json

{
  "status": "ENDED"
}

### 역할 갱신 - 프로젝트 만들때 게이트 웨이에서 프로젝트 어드민으로 바꾸기 위해
PUT http://localhost:8080/accountapi/users/asdf/role
Content-Type: application/json

{
  "role": "PROJECT_ADMIN"
}

### 유저가 속한 프로젝트들 조회
GET http://localhost:8080/users/user1/projects
